version: '3.4'

services:
  movieapi:
    image: movieapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5050:5050
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
